## Array

#### Example 1: Code for initialising numpy array

In [3]:
import numpy as np
a = np.array([0,1,2])
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a[0]

0

In [7]:
a[1]

1

In [8]:
a[2]

2

In [10]:
a[0] = 5
a

array([5, 1, 2])

In [14]:
b = np.array([[0,1,2], [3,4,5]])
b.shape

(2, 3)

In [15]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
print(b[0,0], b[0,1], b[1,0])

0 1 3


#### Example 2: Creating Numpy Array

In [19]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [21]:
c = np.full((3,3), 7)
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [24]:
d = np.random.random((3,3))
d

array([[0.40951441, 0.83507637, 0.27413   ],
       [0.01683393, 0.15580447, 0.73449536],
       [0.63614583, 0.10105277, 0.39677683]])

In [26]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
x = [1,2,3,4,4]
print(x)
f = np.array(x)
f

[1, 2, 3, 4, 4]


array([1, 2, 3, 4, 4])

In [30]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
np.arange(1,8, dtype = np.float)

array([1., 2., 3., 4., 5., 6., 7.])

In [35]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

## Data Types

#### Example 3: Numpy data types

In [41]:
x = np.array([0,1])

In [42]:
y = np.array([2.0, 3.0])

In [47]:
z = np.array([5,6], dtype=np.int64)

In [48]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


## Array indexing

#### Example 4: indexing in numpy

In [55]:
arr = np.array([[-1,2,0,4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])

In [65]:
arr[:2, ::]

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ]])

In [67]:
arr[[0,1,2,3], [3,2,1,0]]

array([4., 6., 0., 3.])

In [70]:
cond = arr > 0
arr[cond]

array([2. , 4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. , 2. ])

## Basic Array Operations

#### Example 5

In [82]:
a = np.array([1,2,5,3])
a+1

array([2, 3, 6, 4])

In [72]:
a-3

array([-2, -1,  2,  0])

In [73]:
a*10

array([10, 20, 50, 30])

In [75]:
a**2

array([ 1,  4, 25,  9], dtype=int32)

In [83]:
a

array([1, 2, 5, 3])

In [85]:
a*=2
a

array([ 4,  8, 20, 12])

In [87]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [89]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Example 6: Unary Operators

In [91]:
a = np.array([[1,5,6], [4,7,2], [3,1,9]])

In [92]:
a.max()

9

In [93]:
a.max(axis = 1)

array([6, 7, 9])

In [94]:
a.min()

1

In [97]:
a.min(axis = 0)

array([1, 1, 2])

In [98]:
a.sum()

38

In [ ]:
# cumulative sum

In [102]:
a.cumsum(axis = 1)

array([[ 1,  6, 12],
       [ 4, 11, 13],
       [ 3,  4, 13]], dtype=int32)

#### Example 7: Binary Operators

In [103]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])

In [ ]:
# elementwise addition

In [104]:
a+b

array([[5, 5],
       [5, 5]])

In [ ]:
# elementwise multiplication

In [105]:
a*b

array([[4, 6],
       [6, 4]])

In [ ]:
# matrix multiplication

In [106]:
a.dot(b)

array([[ 8,  5],
       [20, 13]])

#### Example 8: Universal Functions

In [108]:
a = np.array([0, np.pi/2, np.pi])
np.sin(a)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
Exponent Function: e^x

In [109]:
np.exp(a)

array([ 1.        ,  4.81047738, 23.14069263])

In [110]:
np.sqrt(a)

array([0.        , 1.25331414, 1.77245385])

## Matrix Inverse

#### Example 9

In [120]:
a = np.array([[1,5,6], [4,7,2], [3,1,9]])

In [121]:
inverse = np.linalg.inv(a)
inverse

array([[-0.31937173,  0.20418848,  0.16753927],
       [ 0.15706806,  0.04712042, -0.11518325],
       [ 0.08900524, -0.07329843,  0.06806283]])

# End